# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YZNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'HandyJSON', '4.0.0-beta.1'
pod 'Moya'
  # Pods for YZNews

end
